// frontend-angular/src/app/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent {
  menuAbierto = false;

  toggleMenu() {
    this.menuAbierto = !this.menuAbierto;
  }

  closeMenu() {
    this.menuAbierto = false;
  }
}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand fw-bold" [routerLink]="['/recetas']" (click)="closeMenu()">🍳 Recetas</a>
    <button 
      class="navbar-toggler" 
      type="button" 
      (click)="toggleMenu()"
      [attr.aria-expanded]="menuAbierto">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" [class.show]="menuAbierto">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" [routerLink]="['/recetas']" (click)="closeMenu()">Inicio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" [routerLink]="['/recetas']" (click)="closeMenu()">Todas las Recetas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" [routerLink]="['/nueva-receta']" (click)="closeMenu()">
            <button class="btn btn-primary btn-sm">+ Nueva Receta</button>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

// frontend-react/src/components/Navbar.jsx
import { Link } from 'react-router-dom';

function Navbar() {
  return (
    <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
      <div className="container">
        <Link className="navbar-brand" to="/">🍳 Recetas React</Link>
        <div className="navbar-nav ms-auto">
          <Link className="nav-link" to="/">Listado</Link>
          <Link className="nav-link" to="/nueva">Nueva receta</Link>
        </div>
      </div>
    </nav>
  );
}

export default Navbar;
