// frontend-angular/src/app/components/receta-list/receta-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { forkJoin } from 'rxjs';
import { RecetaService } from '../../services/receta.service';
import { Receta } from '../../models/receta.model';

@Component({
  selector: 'app-receta-list',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './receta-list.component.html',
  styleUrls: ['./receta-list.component.css']
})
export class RecetaListComponent implements OnInit {
  recetas: Receta[] = [];
  recetasFiltradas: Receta[] = [];
  recetasPaginadas: Receta[] = [];
  cargando = false;
  error: string | null = null;
  mostrarError = false;
  exito: string | null = null;

  paginaActual = 1;
  totalPaginas = 1;
  limite = 6;

  busqueda = '';
  categoriaFiltro = '';

  categorias: string[] = [];

  constructor(private recetaService: RecetaService) { }

  ngOnInit(): void {
    this.cargarDatos();
    this.recetaService.cargando$.subscribe(value => {
      this.cargando = value;
    });
    this.recetaService.error$.subscribe(value => {
      this.error = value;
      this.mostrarError = !!value;
    });
  }

  cargarDatos(): void {
    forkJoin([
      this.recetaService.obtenerRecetas(),
      this.recetaService.obtenerCategorias(),
    ]).subscribe({
      next: ([recetas, categorias]) => {
        this.recetas = recetas;
        this.categorias = categorias;
        this.aplicarFiltros();
      },
      error: (err) => {
        console.error('Error al cargar datos:', err);
      }
    });
  }

  aplicarFiltros(): void {
    this.exito = null;
    const texto = this.busqueda.trim().toLowerCase();
    this.paginaActual = 1;

    this.recetasFiltradas = this.recetas.filter((receta) => {
      const coincideBusqueda = !texto
        || receta.nombre.toLowerCase().includes(texto)
        || receta.descripcion.toLowerCase().includes(texto);

      const coincideCategoria = !this.categoriaFiltro
        || receta.categorias.includes(this.categoriaFiltro);

      return coincideBusqueda && coincideCategoria;
    });

    this.calcularPaginacion();
  }

  limpiarFiltros(): void {
    this.busqueda = '';
    this.categoriaFiltro = '';
    this.aplicarFiltros();
  }

  calcularPaginacion(): void {
    this.totalPaginas = Math.max(1, Math.ceil(this.recetasFiltradas.length / this.limite));

    if (this.paginaActual > this.totalPaginas) {
      this.paginaActual = this.totalPaginas;
    }

    const inicio = (this.paginaActual - 1) * this.limite;
    const fin = inicio + this.limite;
    this.recetasPaginadas = this.recetasFiltradas.slice(inicio, fin);
  }

  cambiarPagina(pagina: number): void {
    if (pagina >= 1 && pagina <= this.totalPaginas) {
      this.paginaActual = pagina;
      this.calcularPaginacion();
      window.scrollTo(0, 0);
    }
  }

  eliminarReceta(id?: string): void {
    if (!id) return;
    if (!window.confirm('¿Seguro que deseas eliminar esta receta?')) return;

    this.recetaService.eliminarReceta(id).subscribe({
      next: () => {
        this.exito = 'Receta eliminada correctamente';
        this.recetas = this.recetas.filter((r) => r._id !== id);
        this.aplicarFiltros();
      },
      error: (err) => {
        console.error('Error al eliminar receta:', err);
      }
    });
  }
}

<div class="container py-5">
  <div *ngIf="mostrarError && error" class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Error:</strong> {{ error }}
    <button type="button" class="btn-close" (click)="mostrarError = false"></button>
  </div>

  <div *ngIf="exito" class="alert alert-success alert-dismissible fade show" role="alert">
    {{ exito }}
    <button type="button" class="btn-close" (click)="exito = null"></button>
  </div>

  <div *ngIf="cargando" class="d-flex justify-content-center my-5">
    <div class="spinner-border text-primary" role="status">
      <span class="visually-hidden">Cargando...</span>
    </div>
  </div>

  <div class="row mb-4">
    <div class="col">
      <h1 class="display-4">🍳 Recetas</h1>
      <p class="text-muted">Listado con filtros, paginación y acciones CRUD</p>
    </div>
  </div>

  <div class="card mb-4 shadow-sm">
    <div class="card-header bg-primary text-white">
      <h5 class="mb-0">🔍 Filtros</h5>
    </div>
    <div class="card-body">
      <div class="row g-3">
        <div class="col-md-6">
          <input 
            type="text" 
            class="form-control" 
            placeholder="Buscar por nombre o descripción..."
            [value]="busqueda"
            (input)="busqueda = $any($event.target).value"
            (keyup)="aplicarFiltros()">
        </div>

        <div class="col-md-3">
          <select class="form-select" [value]="categoriaFiltro" (change)="categoriaFiltro = $any($event.target).value">
            <option value="">Todas las categorías</option>
            <option *ngFor="let cat of categorias" [value]="cat">
              {{ cat | titlecase }}
            </option>
          </select>
        </div>

        <div class="col-md-3">
          <button class="btn btn-primary" (click)="aplicarFiltros()">Aplicar</button>
        </div>

        <div class="col-12">
          <button class="btn btn-secondary" (click)="limpiarFiltros()">
            Limpiar filtros
          </button>
        </div>
      </div>
    </div>
  </div>

  <div *ngIf="!cargando && recetasFiltradas.length > 0">
    <div class="row g-4 mb-4">
      <div class="col-md-6 col-lg-4" *ngFor="let receta of recetasPaginadas">
        <div class="card h-100 shadow-sm hover-card">
          <div class="card-body d-flex flex-column">
            <div class="mb-2">
              <span class="badge bg-info ms-1" *ngFor="let cat of receta.categorias">
                {{ cat }}
              </span>
            </div>

            <h5 class="card-title">{{ receta.nombre }}</h5>
            <p class="card-text text-muted small">{{ receta.descripcion | slice:0:80 }}...</p>

            <div class="small text-muted mb-3">
              <div>⭐ {{ receta.valoracion.puntuacion }} / 5</div>
              <div>🗳️ {{ receta.valoracion.votos }} votos</div>
            </div>

            <div class="btn-group mt-auto" role="group">
              <a [routerLink]="['/receta', receta._id]" class="btn btn-sm btn-outline-primary">
                Ver Detalle
              </a>
              <a [routerLink]="['/editar', receta._id]" class="btn btn-sm btn-outline-warning">
                Editar
              </a>
              <button class="btn btn-sm btn-outline-danger" (click)="eliminarReceta(receta._id)">
                Borrar
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <nav aria-label="Paginación" *ngIf="totalPaginas > 1">
      <ul class="pagination justify-content-center">
        <li class="page-item" [class.disabled]="paginaActual === 1">
          <button class="page-link" (click)="cambiarPagina(1)">Primera</button>
        </li>
        <li class="page-item" [class.disabled]="paginaActual === 1">
          <button class="page-link" (click)="cambiarPagina(paginaActual - 1)">Anterior</button>
        </li>

        <li class="page-item" *ngFor="let page of [].constructor(totalPaginas); let i = index"
            [class.active]="i + 1 === paginaActual">
          <button class="page-link" (click)="cambiarPagina(i + 1)">{{ i + 1 }}</button>
        </li>

        <li class="page-item" [class.disabled]="paginaActual === totalPaginas">
          <button class="page-link" (click)="cambiarPagina(paginaActual + 1)">Siguiente</button>
        </li>
        <li class="page-item" [class.disabled]="paginaActual === totalPaginas">
          <button class="page-link" (click)="cambiarPagina(totalPaginas)">Última</button>
        </li>
      </ul>
    </nav>

    <div class="text-center text-muted small mt-3">
      Mostrando {{ (paginaActual - 1) * limite + 1 }}-{{ (paginaActual * limite) > recetasFiltradas.length ? recetasFiltradas.length : (paginaActual * limite) }}
      de {{ recetasFiltradas.length }} recetas
    </div>
  </div>

  <div *ngIf="!cargando && recetasFiltradas.length === 0" class="alert alert-info text-center py-5">
    <h4>😅 Sin resultados</h4>
    <p>No se encontraron recetas con los filtros aplicados.</p>
    <button class="btn btn-primary" (click)="limpiarFiltros()">Limpiar Filtros</button>
  </div>
</div>

// frontend-react/src/components/RecetaList.jsx
import { useEffect, useState } from 'react';
import { recetaService } from '../services/recetaService';
import RecetaCard from './RecetaCard';

function RecetaList() {
  const [recetas, setRecetas] = useState([]);
  const [categorias, setCategorias] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [alert, setAlert] = useState('');

  const [busqueda, setBusqueda] = useState('');
  const [categoria, setCategoria] = useState('');
  const [page, setPage] = useState(1);
  const [limit] = useState(6);
  const [totalPages, setTotalPages] = useState(1);
  const [total, setTotal] = useState(0);

  const loadData = async ({ targetPage = page, targetCategoria = categoria, targetBusqueda = busqueda } = {}) => {
    try {
      setLoading(true);
      setError('');

      const [result, dataCategorias] = await Promise.all([
        recetaService.getPaginated({
          page: targetPage,
          limit,
          categoria: targetCategoria,
          q: targetBusqueda.trim(),
        }),
        recetaService.getCategorias(),
      ]);

      setRecetas(result.status || []);
      setCategorias(dataCategorias);
      setPage(result.pagination?.page || targetPage);
      setTotalPages(result.pagination?.totalPages || 1);
      setTotal(result.pagination?.total || 0);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData({ targetPage: 1 });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const aplicarFiltros = () => {
    loadData({ targetPage: 1 });
  };

  const cambiarPagina = (nextPage) => {
    if (nextPage < 1 || nextPage > totalPages) return;
    loadData({ targetPage: nextPage });
  };

  const eliminar = async (id) => {
    if (!window.confirm('¿Deseas eliminar esta receta?')) return;
    try {
      setLoading(true);
      setError('');
      await recetaService.remove(id);
      setAlert('Receta eliminada correctamente');
      const targetPage = page > 1 && recetas.length === 1 ? page - 1 : page;
      await loadData({ targetPage });
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="container py-4">
      <h1 className="mb-3">Listado de recetas</h1>

      {alert && <div className="alert alert-success">{alert}</div>}
      {error && <div className="alert alert-danger">{error}</div>}

      <div className="card mb-3">
        <div className="card-body row g-2">
          <div className="col-md-6">
            <input
              className="form-control"
              placeholder="Buscar por nombre o descripción"
              value={busqueda}
              onChange={(e) => setBusqueda(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') aplicarFiltros();
              }}
            />
          </div>
          <div className="col-md-4">
            <select className="form-select" value={categoria} onChange={(e) => setCategoria(e.target.value)}>
              <option value="">Todas las categorías</option>
              {categorias.map((cat) => (
                <option key={cat} value={cat}>{cat}</option>
              ))}
            </select>
          </div>
          <div className="col-md-2 d-grid">
            <button className="btn btn-outline-primary" onClick={aplicarFiltros}>Aplicar</button>
          </div>
        </div>
      </div>

      {loading && <div className="text-center py-3"><div className="spinner-border" /></div>}

      {!loading && recetas.length === 0 && (
        <div className="alert alert-info">No hay recetas para mostrar.</div>
      )}

      <div className="row g-3">
        {recetas.map((receta) => (
          <div key={receta._id} className="col-md-6 col-lg-4">
            <RecetaCard receta={receta} onDelete={eliminar} />
          </div>
        ))}
      </div>

      <div className="d-flex justify-content-between align-items-center mt-4">
        <small>Total: {total}</small>
        <div className="btn-group">
          <button className="btn btn-outline-secondary" disabled={page <= 1} onClick={() => cambiarPagina(page - 1)}>
            Anterior
          </button>
          <button className="btn btn-outline-secondary" disabled>
            {page} / {totalPages}
          </button>
          <button className="btn btn-outline-secondary" disabled={page >= totalPages} onClick={() => cambiarPagina(page + 1)}>
            Siguiente
          </button>
        </div>
      </div>
    </div>
  );
}

export default RecetaList;
