// frontend-react/src/components/RecetaForm.jsx
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { recetaService } from '../services/recetaService';

const categorias = ['Española', 'Arroces', 'Tapas', 'Saludable', 'Rápida', 'Postre'];

const initialState = {
  nombre: '',
  descripcion: '',
  ingredientes: '',
  instrucciones: '',
  categorias: [],
  valoracion: {
    puntuacion: 1,
    votos: 1,
  },
};

function RecetaForm() {
  const { id } = useParams();
  const navigate = useNavigate();
  const editMode = Boolean(id);

  const [form, setForm] = useState(initialState);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [fieldErrors, setFieldErrors] = useState({});
  const [touched, setTouched] = useState({});
  const [submitted, setSubmitted] = useState(false);

  useEffect(() => {
    if (!editMode) return;

    const load = async () => {
      try {
        setLoading(true);
        const receta = await recetaService.getById(id);
        setForm({
          ...receta,
          categorias: Array.isArray(receta.categorias) ? receta.categorias : [],
          valoracion: {
            puntuacion: receta.valoracion?.puntuacion ?? 1,
            votos: receta.valoracion?.votos ?? 1,
          },
        });
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };

    load();
  }, [editMode, id]);

  const updateField = (field, value) => {
    setForm((prev) => ({ ...prev, [field]: value }));
    setFieldErrors((prev) => ({ ...prev, [field]: '' }));
  };

  const touchField = (field) => {
    setTouched((prev) => ({ ...prev, [field]: true }));
  };

  const toggleCategoria = (value) => {
    setForm((prev) => {
      const existe = prev.categorias.includes(value);
      const nextCategorias = existe
        ? prev.categorias.filter((item) => item !== value)
        : [...prev.categorias, value];

      setFieldErrors((prevErrors) => ({ ...prevErrors, categorias: '' }));
      setTouched((prevTouched) => ({ ...prevTouched, categorias: true }));
      return { ...prev, categorias: nextCategorias };
    });
  };

  const updateValoracion = (field, value) => {
    setForm((prev) => ({
      ...prev,
      valoracion: {
        ...prev.valoracion,
        [field]: value,
      },
    }));
    setFieldErrors((prev) => ({ ...prev, [field]: '' }));
  };

  const validate = () => {
    const errores = {};

    if (!form.nombre || !form.nombre.trim()) errores.nombre = 'Este campo es obligatorio';
    else if (form.nombre.trim().length < 3) errores.nombre = 'El nombre debe tener al menos 3 caracteres';

    if (!form.descripcion || !form.descripcion.trim()) errores.descripcion = 'Este campo es obligatorio';
    else if (form.descripcion.trim().length < 10) errores.descripcion = 'La descripción debe tener al menos 10 caracteres';

    if (!form.ingredientes || !form.ingredientes.trim()) errores.ingredientes = 'Este campo es obligatorio';
    if (!form.instrucciones || !form.instrucciones.trim()) errores.instrucciones = 'Este campo es obligatorio';
    if (!Array.isArray(form.categorias) || !form.categorias.length) errores.categorias = 'Este campo es obligatorio';

    const puntuacion = Number(form.valoracion?.puntuacion);
    const votos = Number(form.valoracion?.votos);
    if (form.valoracion?.puntuacion === '' || form.valoracion?.puntuacion === null || form.valoracion?.puntuacion === undefined) {
      errores.puntuacion = 'Este campo es obligatorio';
    } else if (Number.isNaN(puntuacion) || puntuacion < 0 || puntuacion > 5) {
      errores.puntuacion = 'La puntuación debe estar entre 0 y 5';
    }

    if (form.valoracion?.votos === '' || form.valoracion?.votos === null || form.valoracion?.votos === undefined) {
      errores.votos = 'Este campo es obligatorio';
    } else if (Number.isNaN(votos) || votos < 0) {
      errores.votos = 'Los votos deben ser 0 o mayor';
    }

    return errores;
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    setError('');
    setSuccess('');
    setSubmitted(true);

    const errores = validate();
    setFieldErrors(errores);
    setTouched({
      nombre: true,
      descripcion: true,
      ingredientes: true,
      instrucciones: true,
      categorias: true,
      puntuacion: true,
      votos: true,
    });

    if (Object.keys(errores).length > 0) {
      setError('Revisa los campos obligatorios del formulario');
      return;
    }

    const payload = {
      nombre: form.nombre.trim(),
      descripcion: form.descripcion.trim(),
      ingredientes: form.ingredientes.trim(),
      instrucciones: form.instrucciones.trim(),
      categorias: form.categorias,
      valoracion: {
        puntuacion: Number(form.valoracion.puntuacion),
        votos: Number(form.valoracion.votos),
      },
    };

    try {
      setLoading(true);
      if (editMode) {
        await recetaService.update(id, payload);
        setSuccess('Receta actualizada correctamente');
      } else {
        await recetaService.create(payload);
        setSuccess('Receta creada correctamente');
      }

      setTimeout(() => navigate('/'), 1000);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="container py-4">
      <h1 className="mb-3">{editMode ? 'Editar receta' : 'Nueva receta'}</h1>

      {error && <div className="alert alert-danger">{error}</div>}
      {success && <div className="alert alert-success">{success}</div>}

      <form onSubmit={handleSubmit} noValidate className="card card-body">
        <div className="row g-3">
          <div className="col-md-6">
            <label className="form-label">Nombre <span className="text-danger">*</span></label>
            <input
              className={`form-control ${(fieldErrors.nombre && (submitted || touched.nombre)) ? 'is-invalid' : ''}`}
              placeholder="Ej: Pasta Carbonara"
              value={form.nombre}
              onChange={(e) => updateField('nombre', e.target.value)}
              onBlur={() => touchField('nombre')}
            />
            {(submitted || touched.nombre) && fieldErrors.nombre && <div className="invalid-feedback">{fieldErrors.nombre}</div>}
          </div>
          <div className="col-md-3">
            <label className="form-label">Puntuación (0-5) <span className="text-danger">*</span></label>
            <input
              type="number"
              className={`form-control ${(fieldErrors.puntuacion && (submitted || touched.puntuacion)) ? 'is-invalid' : ''}`}
              required
              min="0"
              max="5"
              step="0.1"
              value={form.valoracion.puntuacion}
              onChange={(e) => updateValoracion('puntuacion', e.target.value)}
              onBlur={() => touchField('puntuacion')}
            />
            {(submitted || touched.puntuacion) && fieldErrors.puntuacion && <div className="invalid-feedback">{fieldErrors.puntuacion}</div>}
          </div>
          <div className="col-md-3">
            <label className="form-label">Votos <span className="text-danger">*</span></label>
            <input
              type="number"
              className={`form-control ${(fieldErrors.votos && (submitted || touched.votos)) ? 'is-invalid' : ''}`}
              required
              min="0"
              value={form.valoracion.votos}
              onChange={(e) => updateValoracion('votos', e.target.value)}
              onBlur={() => touchField('votos')}
            />
            {(submitted || touched.votos) && fieldErrors.votos && <div className="invalid-feedback">{fieldErrors.votos}</div>}
          </div>

          <div className="col-12">
            <label className="form-label">Categorías <span className="text-danger">*</span></label>
            <div className="d-flex flex-wrap gap-3">
              {categorias.map((item) => (
                <div className="form-check" key={item}>
                  <input
                    id={`cat-${item}`}
                    type="checkbox"
                    className="form-check-input"
                    checked={form.categorias.includes(item)}
                    onChange={() => toggleCategoria(item)}
                  />
                  <label className="form-check-label" htmlFor={`cat-${item}`}>{item}</label>
                </div>
              ))}
            </div>
            {(submitted || touched.categorias) && fieldErrors.categorias && <div className="text-danger small mt-2">{fieldErrors.categorias}</div>}
          </div>

          <div className="col-12">
            <label className="form-label">Descripción <span className="text-danger">*</span></label>
            <textarea
              className={`form-control ${(fieldErrors.descripcion && (submitted || touched.descripcion)) ? 'is-invalid' : ''}`}
              rows="3"
              placeholder="Describe tu receta en detalle..."
              value={form.descripcion}
              onChange={(e) => updateField('descripcion', e.target.value)}
              onBlur={() => touchField('descripcion')}
            />
            <small className="form-text text-muted">{form.descripcion?.length || 0}/1200 caracteres</small>
            {(submitted || touched.descripcion) && fieldErrors.descripcion && <div className="invalid-feedback">{fieldErrors.descripcion}</div>}
          </div>

          <div className="col-md-6">
            <label className="form-label">Ingredientes <span className="text-danger">*</span></label>
            <textarea
              className={`form-control ${(fieldErrors.ingredientes && (submitted || touched.ingredientes)) ? 'is-invalid' : ''}`}
              rows="5"
              value={form.ingredientes}
              onChange={(e) => updateField('ingredientes', e.target.value)}
              onBlur={() => touchField('ingredientes')}
            />
            {(submitted || touched.ingredientes) && fieldErrors.ingredientes && <div className="invalid-feedback">{fieldErrors.ingredientes}</div>}
          </div>

          <div className="col-md-6">
            <label className="form-label">Instrucciones <span className="text-danger">*</span></label>
            <textarea
              className={`form-control ${(fieldErrors.instrucciones && (submitted || touched.instrucciones)) ? 'is-invalid' : ''}`}
              rows="5"
              value={form.instrucciones}
              onChange={(e) => updateField('instrucciones', e.target.value)}
              onBlur={() => touchField('instrucciones')}
            />
            {(submitted || touched.instrucciones) && fieldErrors.instrucciones && <div className="invalid-feedback">{fieldErrors.instrucciones}</div>}
          </div>
        </div>

        <div className="mt-4 d-flex gap-2">
          <button className="btn btn-primary" disabled={loading} type="submit">
            {loading ? 'Guardando...' : editMode ? 'Actualizar' : 'Crear'}
          </button>
          <button className="btn btn-secondary" type="button" onClick={() => navigate('/')}>Cancelar</button>
        </div>
      </form>
    </div>
  );
}

export default RecetaForm;

// frontend-angular/src/app/components/receta-form/receta-form.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AbstractControl, FormBuilder, FormGroup, ReactiveFormsModule, ValidationErrors, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { RecetaService } from '../../services/receta.service';
import { RecetaPayload } from '../../models/receta.model';

@Component({
  selector: 'app-receta-form',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './receta-form.component.html',
  styleUrls: ['./receta-form.component.css']
})
export class RecetaFormComponent implements OnInit {
  private fb = inject(FormBuilder);
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private recetaService = inject(RecetaService);

  formulario!: FormGroup;
  esEdicion = false;
  recetaId: string | null = null;
  cargando = false;
  guardando = false;
  error: string | null = null;
  mostrarError = false;
  mostrarValidaciones = false;
  exito = false;

  categoriasDisponibles = ['Española', 'Arroces', 'Tapas', 'Saludable', 'Rápida', 'Postre'];

  constructor() {
    this.inicializarFormulario();
  }

  ngOnInit(): void {
    this.recetaId = this.route.snapshot.paramMap.get('id');
    if (this.recetaId) {
      this.esEdicion = true;
      this.cargarReceta();
    }

    this.recetaService.cargando$.subscribe(value => {
      this.cargando = value;
    });

    this.recetaService.error$.subscribe(value => {
      this.error = value;
      this.mostrarError = !!value;
    });
  }

  validarCategorias(control: AbstractControl): ValidationErrors | null {
    const value = control.value as string[];
    return Array.isArray(value) && value.length > 0 ? null : { categoriasRequired: true };
  }

  inicializarFormulario(): void {
    this.formulario = this.fb.group({
      nombre: ['', [Validators.required, Validators.minLength(3), Validators.maxLength(120)]],
      descripcion: ['', [Validators.required, Validators.minLength(10), Validators.maxLength(1200)]],
      ingredientes: ['', [Validators.required, Validators.minLength(5)]],
      instrucciones: ['', [Validators.required, Validators.minLength(5)]],
      categorias: [[], [this.validarCategorias]],
      valoracion: this.fb.group({
        puntuacion: [1, [Validators.required, Validators.min(0), Validators.max(5)]],
        votos: [1, [Validators.required, Validators.min(0)]],
      })
    });
  }

  cargarReceta(): void {
    if (!this.recetaId) return;

    this.recetaService.obtenerRecetaPorId(this.recetaId).subscribe({
      next: (receta) => {
        this.formulario.patchValue({
          nombre: receta.nombre,
          descripcion: receta.descripcion,
          ingredientes: receta.ingredientes,
          instrucciones: receta.instrucciones,
          categorias: receta.categorias,
          valoracion: {
            puntuacion: receta.valoracion?.puntuacion ?? 1,
            votos: receta.valoracion?.votos ?? 1,
          },
        });
      },
      error: () => {
        this.error = 'Error al cargar la receta';
        this.mostrarError = true;
      }
    });
  }

  alternarCategoria(categoria: string): void {
    const control = this.formulario.get('categorias');
    const actuales = (control?.value || []) as string[];
    const yaSeleccionada = actuales.includes(categoria);
    const nuevasCategorias = yaSeleccionada
      ? actuales.filter((item) => item !== categoria)
      : [...actuales, categoria];

    control?.setValue(nuevasCategorias);
    control?.markAsTouched();
  }

  guardarReceta(): void {
    this.mostrarValidaciones = true;

    if (this.formulario.invalid) {
      this.formulario.markAllAsTouched();
      this.error = 'Revisa los campos obligatorios';
      this.mostrarError = true;
      return;
    }

    this.guardando = true;
    const formValue = this.formulario.value;
    const datos: RecetaPayload = {
      nombre: formValue.nombre?.trim(),
      descripcion: formValue.descripcion?.trim(),
      ingredientes: formValue.ingredientes?.trim(),
      instrucciones: formValue.instrucciones?.trim(),
      categorias: formValue.categorias,
      valoracion: {
        puntuacion: Number(formValue.valoracion?.puntuacion),
        votos: Number(formValue.valoracion?.votos),
      },
    };

    const operacion = this.esEdicion
      ? this.recetaService.actualizarReceta(this.recetaId!, datos)
      : this.recetaService.crearReceta(datos);

    operacion.subscribe({
      next: () => {
        this.exito = true;
        this.guardando = false;
        setTimeout(() => {
          this.router.navigate(['/recetas']);
        }, 1200);
      },
      error: (err) => {
        this.guardando = false;
        const mensajeError = err.error?.status || 'Error al guardar la receta';
        this.error = mensajeError;
        this.mostrarError = true;
      }
    });
  }

  cancelar(): void {
    this.router.navigate(['/recetas']);
  }

  getErrorMessage(fieldName: string): string {
    const control = this.formulario.get(fieldName);
    if (!control || !control.errors || !control.touched) return '';

    if (control.errors['required']) return 'Este campo es obligatorio';
    if (control.errors['minlength']) {
      const minLength = control.errors['minlength'].requiredLength;
      return `Mínimo ${minLength} caracteres`;
    }
    if (control.errors['maxlength']) {
      const maxLength = control.errors['maxlength'].requiredLength;
      return `Máximo ${maxLength} caracteres`;
    }
    if (control.errors['min']) {
      const min = control.errors['min'].min;
      return `El valor mínimo es ${min}`;
    }
    if (control.errors['max']) {
      const max = control.errors['max'].max;
      return `El valor máximo es ${max}`;
    }
    if (control.errors['categoriasRequired']) return 'Selecciona al menos una categoría';
    return 'Campo inválido';
  }

  tieneError(fieldName: string): boolean {
    const control = this.formulario.get(fieldName);
    return !!(control && control.invalid && control.touched);
  }

}

<div class="container py-5">
  <div *ngIf="mostrarError && error" class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Error:</strong> {{ error }}
    <button type="button" class="btn-close" (click)="mostrarError = false"></button>
  </div>

  <div *ngIf="exito" class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>¡Éxito!</strong> Receta {{ esEdicion ? 'actualizada' : 'creada' }} correctamente. Redirigiendo...
    <button type="button" class="btn-close" (click)="exito = false"></button>
  </div>

  <div class="mb-4">
    <h1 class="display-4 mb-2">
      {{ esEdicion ? '✏️ Editar Receta' : '➕ Nueva Receta' }}
    </h1>
    <p class="text-muted">Formulario reactivo con validaciones visuales y funcionales</p>
  </div>

  <form [formGroup]="formulario" (ngSubmit)="guardarReceta()" *ngIf="!cargando">
    <div class="row">
      <div class="col-lg-8">
        <div class="card mb-4 shadow-sm">
          <div class="card-header bg-primary text-white">
            <h5 class="mb-0">📝 Información Básica</h5>
          </div>
          <div class="card-body">
            <div class="mb-3">
              <label for="nombre" class="form-label">Nombre <span class="text-danger">*</span></label>
              <input 
                type="text" 
                class="form-control" 
                id="nombre"
                formControlName="nombre"
                [class.is-invalid]="tieneError('nombre')"
                placeholder="Ej: Pasta Carbonara">
              <div class="invalid-feedback" *ngIf="tieneError('nombre')">
                {{ getErrorMessage('nombre') }}
              </div>
            </div>

            <div class="mb-3">
              <label for="descripcion" class="form-label">Descripción <span class="text-danger">*</span></label>
              <textarea 
                class="form-control" 
                id="descripcion"
                formControlName="descripcion"
                [class.is-invalid]="tieneError('descripcion')"
                rows="4"
                placeholder="Describe tu receta en detalle..."></textarea>
              <small class="form-text text-muted">
                {{ formulario.get('descripcion')?.value?.length || 0 }}/1200 caracteres
              </small>
              <div class="invalid-feedback" *ngIf="tieneError('descripcion')">
                {{ getErrorMessage('descripcion') }}
              </div>
            </div>
          </div>
        </div>

        <div class="card mb-4 shadow-sm">
          <div class="card-header bg-success text-white">
            <h5 class="mb-0">📋 Ingredientes <span class="text-danger">*</span></h5>
          </div>
          <div class="card-body">
            <textarea
              class="form-control"
              rows="5"
              formControlName="ingredientes"
              [class.is-invalid]="tieneError('ingredientes')"
              placeholder="Ej: Arroz, pollo, tomate, aceite..."></textarea>
            <div class="invalid-feedback" *ngIf="tieneError('ingredientes')">
              {{ getErrorMessage('ingredientes') }}
            </div>
          </div>
        </div>

        <div class="card mb-4 shadow-sm">
          <div class="card-header bg-info text-white">
            <h5 class="mb-0">👨‍🍳 Instrucciones <span class="text-danger">*</span></h5>
          </div>
          <div class="card-body">
            <textarea
              class="form-control"
              rows="5"
              formControlName="instrucciones"
              [class.is-invalid]="tieneError('instrucciones')"
              placeholder="Describe cómo preparar la receta paso a paso"></textarea>
            <div class="invalid-feedback" *ngIf="tieneError('instrucciones')">
              {{ getErrorMessage('instrucciones') }}
            </div>
          </div>
        </div>
      </div>

      <div class="col-lg-4">
        <div class="card mb-4 shadow-sm">
          <div class="card-header bg-info text-white">
            <h5 class="mb-0">⚙️ Detalles</h5>
          </div>
          <div class="card-body">
            <div class="mb-3">
              <label class="form-label">Categorías <span class="text-danger">*</span></label>
              <div class="d-flex flex-wrap gap-2">
                <div class="form-check" *ngFor="let cat of categoriasDisponibles">
                  <input
                    class="form-check-input"
                    type="checkbox"
                    [id]="'cat-' + cat"
                    [checked]="formulario.get('categorias')?.value?.includes(cat)"
                    (change)="alternarCategoria(cat)"
                  >
                  <label class="form-check-label" [for]="'cat-' + cat">{{ cat }}</label>
                </div>
              </div>
              <div class="text-danger small mt-2" *ngIf="tieneError('categorias')">
                {{ getErrorMessage('categorias') }}
              </div>
            </div>

            <div formGroupName="valoracion">
              <div class="mb-3">
                <label for="puntuacion" class="form-label">Puntuación (0-5) <span class="text-danger">*</span></label>
                <input 
                  type="number"
                  class="form-control"
                  id="puntuacion"
                  formControlName="puntuacion"
                  min="0"
                  max="5"
                  step="0.1"
                  [class.is-invalid]="tieneError('valoracion.puntuacion')">
                <div class="invalid-feedback" *ngIf="tieneError('valoracion.puntuacion')">
                  {{ getErrorMessage('valoracion.puntuacion') }}
                </div>
              </div>

              <div class="mb-3">
                <label for="votos" class="form-label">Votos <span class="text-danger">*</span></label>
                <input 
                  type="number" 
                  class="form-control" 
                  id="votos"
                  formControlName="votos"
                  [class.is-invalid]="tieneError('valoracion.votos')"
                  min="0">
                <div class="invalid-feedback" *ngIf="tieneError('valoracion.votos')">
                  {{ getErrorMessage('valoracion.votos') }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row mt-4">
      <div class="col">
        <button 
          type="submit" 
          class="btn btn-primary btn-lg me-2"
          [disabled]="guardando">
          <span *ngIf="!guardando">
            {{ esEdicion ? '💾 Actualizar Receta' : '➕ Crear Receta' }}
          </span>
          <span *ngIf="guardando">
            <span class="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>
            Guardando...
          </span>
        </button>
        <button 
          type="button" 
          class="btn btn-secondary btn-lg"
          (click)="cancelar()"
          [disabled]="guardando">
          Cancelar
        </button>
      </div>
    </div>
  </form>

  <div *ngIf="cargando" class="d-flex justify-content-center py-5">
    <div class="spinner-border text-primary" role="status">
      <span class="visually-hidden">Cargando...</span>
    </div>
  </div>
</div>
